---
title: "spdaily"
author: "Daniel Zhou"
date: "2/21/2020"
output: html_document
---
```{r}
library(tidyverse)
library(purrr)
library(lubridate)
library(data.table)
```

```{r}
combine <- read.csv(file = 'combine.csv')
```

```{r}
combine=combine %>%
  select(date,CUSIP,RETX,sprtrn)
combine<-combine %>% arrange(CUSIP,date)
```

```{r}
fwrite(combine,"combinenona.csv")
```

```{r}
combine$month=month(ymd(combine$date))
combine$year=year(ymd(combine$date))
```

```{r}
y = read.csv(file = 'y.csv')
keydate=sort(unique(y$date))
tickers = unique(combine$CUSIP)
```

```{r}
ktable <- data.frame("date"=expand.grid(keydate,tickers)[,1],"CUSIP"=expand.grid(keydate,tickers)[,2],"alpha"=NA,"beta"=NA)
```




```{r}
ktable[which((ktable$CUSIP==tickers[5])&(ktable$date==combineticker[81,1])),4]
```




```{r warning=FALSE}
k=42
for (t in 1:length(tickers)){
  combineticker <- combine[combine$CUSIP==tickers[t],]
  rownames(combineticker) <- 1:nrow(combineticker)
  for (i in 1:dim(combineticker)[1]){
    if (i>k){
      if (combineticker[i,1] %in% keydate){
        #j = which(keydate %in% combine[i,])
        tmp = combine[(i-k):i,]
        mod = model(tmp)
        ktable[which((ktable$CUSIP==tickers[t])&(ktable$date==combineticker[i,1])),3]=alpha(mod)
        ktable[which((ktable$CUSIP==tickers[t])&(ktable$date==combineticker[i,1])),4]=beta(mod)
        #ktable[j,2]=tmp
        #ktable[which((ktable$CUSIP==tickers[t])&(ktable$date==combineticker[i,1])),3]=tmp
        
    }
    }
  }

 
}
```


```{r}
bycusip <- combine %>% 
  group_by(CUSIP, year,month) %>% 
  nest()
```

```{r}
model <- function(df) {
  lm(RETX ~ sprtrn, data = df)
}
alpha <- function(model){
  coefficients(model)[[1]]
}
beta <- function(model){
  coefficients(model)[[2]]
}
```


```{r}
bycusip <- bycusip %>% 
  mutate(model1 = map(data, model)) %>% 
  mutate(alpha=map(model1,alpha)) %>% 
  mutate(beta=map(model1,beta)) %>% 
  select(-data) %>% 
  select(CUSIP,month,year,alpha,beta) 
```

```{r}
y = read.csv(file = 'y.csv')
y$month=month(ymd(y$date))
y$year=year(ymd(y$date))
```

```{r}
merge(bycusip, y, by=c("month","year"))
```

```{r}
fwrite(bycusip,"k30.csv")
```




